name: Issue Open Check

on:
  issues:
    types: [opened]

permissions:
  contents: read

env:
  default: 'bug'
  words: ['fix', 'bug', 'error']

jobs:
  issue-open-check:
    permissions:
      issues: write  # for actions-cool/issues-helper to update issues
    runs-on: ubuntu-latest
    steps:
      - name: Check Title
        id: check-title
        run: |
          title="${{ github.event.issue.title }}"
          for word in "${{ env.words[@] }}"; do
            if [[ $title == *"$word"* ]]; then
              echo "Issue 标题包含关键词: $word"
              echo "::set-env name=default::$word"
              break
            fi
          done


      # - name: add label
      #   uses: actions-cool/issues-helper@v3
      #   with:
      #     actions: 'add-labels'
      #     issue-number: ${{ github.event.issue.number }}
      #     labels: ${{ steps.check-title.outputs.default }}

      # - name: check invalid
      #   if: (contains(github.event.issue.body, 'Step to Reproduce') == false)  && (github.event.label.name != 'enhancement')
      #   uses: actions-cool/issues-helper@v3
      #   with:
      #     actions: 'create-comment,add-labels,close-issue'
      #     issue-number: ${{ github.event.issue.number }}
      #     labels: 'closed:invalid'
      #     body: |
      #       Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not include reproduce step.

