name: Issue Open Check

on:
  issues:
    types: [opened]

permissions:
  contents: read

env:
  DEFAULT: bug
  WORDS: |
    enhancement
    bugfix
    feature

jobs:
  issue-open-check:
    permissions:
      issues: write  # for actions-cool/issues-helper to update issues
    runs-on: ubuntu-latest
    steps:
      - name: Check Issue Title
        id: check-title
        uses: actions/github-script@v4
        with:
          script: |
            const title = github.context.payload.issue.title.toLowerCase();
            const values = process.env.ARRAY_VALUES.toLowerCase().split('\n');
            for (const value of values) {
              if (title.includes(value.trim())) {
                console.log(`Found value: ${value.trim()}`);
                console.log(`::set-env name=DEFAULT_VALUE::${value.trim()}`);
                break;
              }
            }

      # - name: add label
      #   uses: actions-cool/issues-helper@v3
      #   with:
      #     actions: 'add-labels'
      #     issue-number: ${{ github.event.issue.number }}
      #     labels: ${{ steps.check-title.outputs.default }}

      # - name: check invalid
      #   if: (contains(github.event.issue.body, 'Step to Reproduce') == false)  && (github.event.label.name != 'enhancement')
      #   uses: actions-cool/issues-helper@v3
      #   with:
      #     actions: 'create-comment,add-labels,close-issue'
      #     issue-number: ${{ github.event.issue.number }}
      #     labels: 'closed:invalid'
      #     body: |
      #       Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not include reproduce step.

