name: Issue Open Check

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  issue-open-check:
    permissions:
      issues: write  # for actions-cool/issues-helper to update issues
    runs-on: ubuntu-latest
    env:
      LABELS: 'api,ui,treesitter,lsp,docmentaion,winbar'
      DEFAULT: 'bug'
    steps:
      - name: Get label
        run: |
          IFS=',' read -ra LABELS_ARR <<< "$LABELS"

          for word in "${LABELS_ARR[@]}"; do
            if [[ "${{ github.event.issue.title }}" == *"$word"* ]]; then
              export DEFAULT=$word
              break
            fi
          done

      - name: add label
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          issue-number: ${{ github.event.issue.number }}
          labels: ${{env.DEFAULT}}

      - name: check invalid
        if: (contains(github.event.issue.body, 'Step to Reproduce') == false)  && (github.event.label.name != 'enhancement')
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,add-labels,close-issue'
          issue-number: ${{ github.event.issue.number }}
          labels: 'closed:invalid'
          body: |
            Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not include reproduce step.

