name: Issue Open Check

on:
  issues:
    types: [opened]

permissions:
  contents: read

env:
  DEFAULT: bug
  WORDS: |
    enhancement
    bugfix
    feature

jobs:
  issue-open-check:
    permissions:
      issues: write  # for actions-cool/issues-helper to update issues
    runs-on: ubuntu-latest
    steps:
      - name: 检查 Issue 标题
        id: check-issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = context.payload.issue.title;
            const keywords = ['fix', 'bug', 'error']; // 要检查的关键词
            const regex = new RegExp(`\\b(${keywords.join('|')})\\b`, 'i');
            const match = title.match(regex);

            if (match) {
              console.log(`匹配到关键词：${match[0]}`);
              core.setOutput('keyword', match[0]); // 将关键词输出到变量中
            }

      # - name: add label
      #   uses: actions-cool/issues-helper@v3
      #   with:
      #     actions: 'add-labels'
      #     issue-number: ${{ github.event.issue.number }}
      #     labels: ${{ steps.check-title.outputs.default }}

      # - name: check invalid
      #   if: (contains(github.event.issue.body, 'Step to Reproduce') == false)  && (github.event.label.name != 'enhancement')
      #   uses: actions-cool/issues-helper@v3
      #   with:
      #     actions: 'create-comment,add-labels,close-issue'
      #     issue-number: ${{ github.event.issue.number }}
      #     labels: 'closed:invalid'
      #     body: |
      #       Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not include reproduce step.

