name: Issue Open Check

on:
  issues:
    types: [opened]

permissions:
  contents: read

env:
  LABELS: |
    api
    ui
    treesitter
    lsp
    docmentaion
    winbar
  DEFAULT: 'bug'

jobs:
  issue-open-check:
    permissions:
      issues: write  # for actions-cool/issues-helper to update issues
    runs-on: ubuntu-latest
    steps:
      - name: Get label
        run: |
          words=("api", "lsp")

          default="bug"

          for word in "${words[@]}"; do
            if [[ ${{ github.event.issue.title}} == *"$word"* ]]; then
              default="$word"
              break
            fi
          done

          # 将 default 变量输出到标准输出和 Action 输出中
          echo "::set-output name=default::$default"
          echo "default=$default"

      - name: add label
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          issue-number: ${{ github.event.issue.number }}
          labels:  ${{ steps.first-action.outputs.default }}

      - name: check invalid
        if: (contains(github.event.issue.body, 'Step to Reproduce') == false)  && (github.event.label.name != 'enhancement')
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,add-labels,close-issue'
          issue-number: ${{ github.event.issue.number }}
          labels: 'closed:invalid'
          body: |
            Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not include reproduce step.

