name: Issue Open Check

on:
  issues:
    types: [opened]

permissions:
  contents: read

env:
  DEFAULT: "bug"
  WORDS: ["fix", "issue", "bug"]

jobs:
  issue-open-check:
    permissions:
      issues: write  # for actions-cool/issues-helper to update issues
    runs-on: ubuntu-latest
    steps:
      - name: 第一个 Action
        id: first-action
        run: |
          words=("fix" "bug" "issue")
          for word in "${words[@]}"; do
            if [[ "${{ github.event.issue.title }}" == *"$word"* ]]; then
              echo "检测到关键字：$word"
              echo "::set-output name=default::$word"
              exit 0
            fi
          done
          echo "未检测到关键字"
          echo "::set-output name=default::bug"
        shell: bash
        outputs:
          default: ${{ steps.first-action.outputs.default }}
            
      - name: 第二个 Action
        id: second-action
        uses: my-org/my-repo/my-action@v1
        with:
          default: ${{ steps.first-action.outputs.default }}

      # - name: add label
      #   uses: actions-cool/issues-helper@v3
      #   with:
      #     actions: 'add-labels'
      #     issue-number: ${{ github.event.issue.number }}
      #     labels: ${{ steps.check-title.outputs.default }}

      # - name: check invalid
      #   if: (contains(github.event.issue.body, 'Step to Reproduce') == false)  && (github.event.label.name != 'enhancement')
      #   uses: actions-cool/issues-helper@v3
      #   with:
      #     actions: 'create-comment,add-labels,close-issue'
      #     issue-number: ${{ github.event.issue.number }}
      #     labels: 'closed:invalid'
      #     body: |
      #       Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not include reproduce step.

