name: Issue Open Check

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  issue-open-check:
    permissions:
      issues: write  # for actions-cool/issues-helper to update issues
    runs-on: ubuntu-latest
    steps:
      - name: add api label
        if: (contains(github.event.issue.title, 'api') == true)
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          issue-number: ${{ github.event.issue.number }}
          labels: 'api'

      - name: add lua label
        if: (contains(github.event.issue.title, 'lua') == true)
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          issue-number: ${{ github.event.issue.number }}
          labels: 'lua'

      - name: add ui label
        if: (contains(github.event.issue.title, 'ui') == true)
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          issue-number: ${{ github.event.issue.number }}
          labels: 'ui'

      - name: add treesitter label
        if: (contains(github.event.issue.title, 'treesitter') == true)
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          issue-number: ${{ github.event.issue.number }}
          labels: 'treesitter'

      - name: add lsp label
        if: (contains(github.event.issue.title, 'lsp') == true)
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          issue-number: ${{ github.event.issue.number }}
          labels: 'treesitter'

      - name: add doc label
        if: (contains(github.event.issue.title, 'doc') == true)
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          issue-number: ${{ github.event.issue.number }}
          labels: 'docmentation'

      - name: check invalid
        if: (contains(github.event.issue.body, 'Step to Reproduce') == false)
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,add-labels,close-issue'
          issue-number: ${{ github.event.issue.number }}
          labels: 'closed:invalid'
          body: |
            Hello @${{ github.event.issue.user.login }}, your issue has been closed because it does not include reproduce step.

